### ISSUE TITLE
[config] 2021-2022第二学期是在2022年

### ISSUE THREAD

**Issue by wr786** [AllanChain/syllabus-CE#1]
https://github.com/AllanChain/syllabus-CE/blob/a32ce9ad39c083a5ea1d157e617afa3a52ebdaa2/src/config.js#L2-L4

2022年了，不是2021-2-21，是2022-2-21。

**Comment by AllanChain** [comment]
感谢提醒，已经修复。

**Comment by AllanChain** [comment]
(掉课比较多，自己还没生成过日历 :joy:
